### ISSUE TITLE
ServerSide `created_at` and `updated_at`

### ISSUE THREAD

**Issue by dagher41** [aaronjohnscott/TodoList#2]
When a todo is created the server side code should define the `created_at` and `update_at` fields on that todo. These should not be defined by the user. When the user creates a todo the created_at and updated_at fields should be set to the current date/time. If a user edits the todo, only the `updated_at` should be updated to the current datetime.

**Comment by aaronjohnscott** [comment]
Not sure how to update the variable of updated when the actually item is updated...

**Comment by dagher41** [comment]
@aaronjohnscott ok we'll talk about it later today
